// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6sewF5QcUbws5UZiLa8vuwjpQLSYdsLw',
    appId: '1:89775976245:web:99a568dc31096af6bd667c',
    messagingSenderId: '89775976245',
    projectId: 'flutter-ecommerce-d935f',
    authDomain: 'flutter-ecommerce-d935f.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-d935f.appspot.com',
    measurementId: 'G-KE01QJ2J5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdWR7_ML1HTQb12uBCIySSmOMrZozOoE',
    appId: '1:89775976245:android:ee38f9694d431826bd667c',
    messagingSenderId: '89775976245',
    projectId: 'flutter-ecommerce-d935f',
    storageBucket: 'flutter-ecommerce-d935f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDONKx1bUikhwy-1IVo3ZijHei77nz5lQQ',
    appId: '1:89775976245:ios:47840c8e546e4e1fbd667c',
    messagingSenderId: '89775976245',
    projectId: 'flutter-ecommerce-d935f',
    storageBucket: 'flutter-ecommerce-d935f.appspot.com',
    iosBundleId: 'com.example.windoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDONKx1bUikhwy-1IVo3ZijHei77nz5lQQ',
    appId: '1:89775976245:ios:d72615b0f6dcf82bbd667c',
    messagingSenderId: '89775976245',
    projectId: 'flutter-ecommerce-d935f',
    storageBucket: 'flutter-ecommerce-d935f.appspot.com',
    iosBundleId: 'com.example.windoApp.RunnerTests',
  );
}
